services:
    grafana:
      container_name: ${APP_NAME_INTERNAL}_grafana
      image: grafana/grafana:${GRAFANA_VERSION}
      volumes:
        - ${APP_PATH_ROOT}grafana:/var/lib/grafana
        - ${APP_PATH_ROOT}provisioning:/etc/grafana/provisioning/
      environment:
        - VIRTUAL_HOST=${DOMAINS}
        - VIRTUAL_PORT=80
      extends:
          file: ${WEX_COMPOSE_YML_DEFAULT}
          service: default