services:
    collabora:
        extends:
            file: ${WEX_COMPOSE_YML_DEFAULT}
            service: default
        container_name: '${APP_NAME_INTERNAL}_collabora'
        image: 'collabora/code:${COLLABORA_VERSION}'
        ports:
            - "9980:9980"
        extra_hosts:
          - "${DOMAIN_MAIN}:${HOST_IP}"
        environment:
            - VIRTUAL_HOST=${DOMAIN_MAIN}
            - VIRTUAL_PROTO=https
            - LETSENCRYPT_HOST=${DOMAIN_MAIN}
            - LETSENCRYPT_EMAIL=${EMAIL}
            - domain=${DOMAIN_MAIN}
            # Should be overridden on production
            - username=admin
            - password=admin
