services:
    onlyoffice:
        container_name: '${APP_NAME_INTERNAL}_onlyoffice'
        image: 'onlyoffice/documentserver:${ONLYOFFICE_DOCUMENT_SERVER_VERSION}'
        ports:
            # MPP-compatible instant messaging client (for ONLYOFFICE Talk correct work)
            - "5222:5222"
        environment:
            - VIRTUAL_HOST=${DOMAINS}
            - VIRTUAL_PORT=80
        volumes:
            - ${APP_PATH_ROOT}logs:/var/log/onlyoffice
            - ${APP_PATH_ROOT}data:/var/www/onlyoffice/Data
        extends:
            file: ${WEX_COMPOSE_YML_DEFAULT}
            service: default
