services:
  jenkins:
    extends:
        file: ${WEX_COMPOSE_YML_DEFAULT}
        service: default
    container_name: '${APP_NAME_INTERNAL}_jenkins'
    image: 'jenkins/jenkins:${JENKINS_VERSION}'
    ports:
      - "50000:50000"
    environment:
      - VIRTUAL_HOST=${DOMAIN_MAIN}
      - VIRTUAL_PORT=8080
    volumes:
      - ${APP_PATH_ROOT}config:/jenkins_config
      - ${APP_PATH_ROOT}home:/var/jenkins_home
    extends:
        file: ${WEX_COMPOSE_YML_DEFAULT}
        service: default
