services:
  matomo:
    container_name: '${APP_NAME_INTERNAL}_matomo'
    image: 'matomo:${MATOMO_VERSION}'
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=${DOMAINS}
      - VIRTUAL_PORT=80
      # Database
      - MATOMO_DATABASE_HOST=${MYSQL_DB_HOST}
      - MATOMO_DATABASE_DBNAME=${MYSQL_DB_NAME}
      - MATOMO_DATABASE_USERNAME=${MYSQL_DB_USER}
      - MATOMO_DATABASE_PASSWORD=${MYSQL_DB_PASSWORD}
    volumes:
      - ${APP_PATH_ROOT}data:/var/www/html
    extends:
        file: ${WEX_COMPOSE_YML_DEFAULT}
        service: default
