        extends:
          file: ${WEX_COMPOSE_YML_NEXTCLOUD}
          service: nextcloud
        depends_on:
          - ${APP_NAME}_maria_10
# Define here default admin user credentials.
#        environment:
#          - NEXTCLOUD_ADMIN_USER=admin
#          - NEXTCLOUD_ADMIN_PASSWORD=supersecretpassword