version: '2'

services:
    rocketchat:
        image: rocket.chat:${ROCKETCHAT_VERSION}
        restart: unless-stopped
        container_name: ${APP_NAME_INTERNAL}_rocketchat
        environment:
          - VIRTUAL_HOST=${APP_NAME}.wex
          - ROOT_URL=http://localhost:3000
          - MONGO_URL=mongodb://${APP_NAME_INTERNAL}_mongo:27017/rocketchat
          - MONGO_OPLOG_URL=mongodb://${APP_NAME_INTERNAL}_mongo:27017/local
          - MAIL_URL=smtp://smtp.mailgun.org
        volumes:
          - ${APP_PATH_ROOT}/uploads:/app/uploads
        networks:
          - wex_net

    hubot:
        image: rocketchat/hubot-rocketchat:v1.0.11
        restart: unless-stopped
        container_name: ${APP_NAME_INTERNAL}_rocketchat_hubot
        environment:
          - ROCKETCHAT_URL=${APP_NAME_INTERNAL}_rocketchat:3000
          - ROCKETCHAT_ROOM=GENERAL
          - ROCKETCHAT_USER=hubot
          - ROCKETCHAT_PASSWORD=vchgdsvcghdvcdsjvcds
          - BOT_NAME=hubot
          - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics
        volumes:
          - ${APP_PATH_ROOT}/hubot/scripts:/home/hubot/scripts
        networks:
          - wex_net