services:
    rocketchat:
        image: rocket.chat:${ROCKETCHAT_VERSION}
        container_name: ${APP_NAME_INTERNAL}_rocketchat
        volumes:
          - ${APP_PATH_ROOT}/uploads:/app/uploads
        extends:
            file: ${WEX_COMPOSE_YML_DEFAULT}
            service: default
        depends_on:
          - ${APP_NAME}_mongo_6
