services:
    nextcloud:
        container_name: '${CONTEXT_NAME}_nextcloud'
        image: nextcloud:${NEXTCLOUD_VERSION}
        environment:
          - VIRTUAL_HOST=${APP_NAME}.wex
          - MYSQL_HOST=${MYSQL_DB_HOST}
          - MYSQL_DATABASE=${MYSQL_DB_NAME}
          - MYSQL_USER=${MYSQL_DB_USER}
          - MYSQL_PASSWORD=${MYSQL_DB_PASSWORD}
        volumes:
            - ${CONTEXT_DIR}data:/var/www/html
            - ${CONTEXT_DIR}extra-addons:/mnt/extra-addons
            - ${CONTEXT_DIR}config.php:/var/www/html/config/wex.config.php
        extends:
            file: ${SERVICE_DEFAULT_YML_ENV}
            service: default
