services:
    gitlab:
      container_name: ${APP_NAME_INTERNAL}_gitlab
      image: gitlab/gitlab-ce:${GITLAB_VERSION}
      hostname: ${DOMAIN_MAIN}
      ports:
        - '4567:22'
      volumes:
        - ${APP_PATH_ROOT}backups:/var/opt/gitlab/backups
        - ${APP_PATH_ROOT}config:/etc/gitlab
        - ${APP_PATH_ROOT}logs:/var/log/gitlab
        - ${APP_PATH_ROOT}data:/var/opt/gitlab
      environment:
        - VIRTUAL_HOST=${DOMAINS}
        - SMTP_DOMAIN=${DOMAIN_MAIN}
        - VIRTUAL_PORT=80
        - GITLAB_SHELL_SSH_PORT=4567
      extends:
          file: ${WEX_COMPOSE_YML_DEFAULT}
          service: default